var BTQuestions;
BTQuestions = [
  "Describe a perfect day",
  "Do you want your children to be like you? Why?",
  "Have you ever had a near-death experience?",
  "How are you making a difference in the world?",
  "How do you define true happiness?",
  "How do you feel about birthdays?",
  "How do you show love?",
  "If someone gave you $10,000 to spend, what would you do with it?",
  "If you could invite three famous people to your home for dinner, who would they be?",
  "If you could talk to everyone in the world what would you say?",
  "If you had 24 hours left to live, who would you be with in 23 hours?",
  "If you had 30 seconds to talk to the world what would you say?",
  "If you were to go back in history and live as someone else, who would it be, and why?",
  "If you were to go back in history and live, which time period, and why?",
  "What advice would you give your younger self?",
  "What advice would you offer to yourself five years ago? One year ago? Today?",
  "What are you curious about lately?",
  "What are you proud of?",
  "What are you thankful for at this very moment?",
  "What could you do today that you couldn't do a year ago?",
  "What do you fear?",
  "What do you hope to achieve in 5 years?",
  "What do you spend too much time doing? What don’t you spend enough time doing?",
  "What do you think about when you wake up?",
  "What do you value that doesn't cost money?",
  "What do you want to change in the world?",
  "What do you want to do before you die?",
  "What do you want to do before you die?",
  "What do you wish more people knew about you?",
  "What does home mean to you?",
  "What does love mean to you?",
  "What does success mean to you?",
  "What does this world need more of?",
  "What happened to your childhood dream?",
  "What has been your favourite age so far and why?",
  "What have you started but never finished? Why?",
  "What have you witnessed that has strengthened your faith in humanity?",
  "What is a misconception that people have about you?",
  "What is a quirk that your family has?",
  "What is holding you back from doing the things you really want to do?",
  "What is one question you would ask a fortune teller?",
  "What is something new you have recently tried?",
  "What is something new you recently tried and enjoyed?",
  "What is something you know you do differently than most people?",
  "What is the best gift someone can give you?",
  "What is the best gift that someone can give you?",
  "What is the kindliest thing someone has ever done for you?",
  "What is the most important lesson you have learnt?",
  "What is the strangest thing you have eaten?",
  "What is your biggest fear?",
  "What is your earliest memory of achievement?",
  "What is your favourite place in the world?",
  "What is your greatest strength?",
  "What is your happiest memory?",
  "What is your next great adventure?",
  "What is your next great adventure?",
  "What is your number one priority today?",
  "What makes you feel really alive?",
  "What object would you save if your house was on fire?",
  "What were you doing the last time you lost track of time?",
  "What’s one thing that could happen today that would make it great?",
  "Where do you find peace?",
  "Where would you like to wake up Tomorrow?",
  "Who do you need to get in touch with because it’s been too long?",
  "END"
];

