var BTQuestions;
BTQuestions = [
  "Describe your perfect day",
  "Do you want your children to be like you? Why?",
  "Have you ever had a near-death experience?",
  "Have you ever done something in a hurry and regretted it?",
  "How are you making a difference in the world?",
  "How do you define true happiness?",
  "How do you feel about birthdays?",
  "How do you show love?",
  "If someone gave you $10,000 to spend, what would you do with it?",
  "If you could create your own country, what would it be like?",
  "If you could invite three famous people to your home for dinner, who would they be?",
  "If you could talk to everyone in the world what would you say?",
  "If you had 24 hours left to live, who would you be with in 23 hours?",
  "If you had 30 seconds to talk to the world what would you say?",
  "If you were to go back in history and live as someone else, who would it be, and why?",
  "If you were to go back in history and live, which time period, and why?",
  "If your life was a book, what would be it's title?",
  "Is there anyone in your life that you admire? Why?",
  "What advice would you give your younger self?",
  "What advice would you offer to yourself five years ago?",
  "What are you curious about lately?",
  "What are you looking forward to?",
  "What are you passionate about?",
  "What are you proud of?",
  "What are you thankful for at this very moment?",
  "What concerns you about the future?",
  "What could you do today that you couldn't do a year ago?",
  "What do you fear?",
  "What do you fight for?",
  "What do you have that you cannot live without?",
  "What do you hope to achieve in 5 years?",
  "What do you miss?",
  "What do you most need help with?",
  "What do you spend too much time doing?",
  "What do you think about when you wake up?",
  "What do you value that doesn't cost money?",
  "What do you want the world to remember about you?",
  "What do you want to change in the world?",
  "What do you want to do before you die?",
  "What do you wish more people knew about you?",
  "What does home mean to you?",
  "What does love mean to you?",
  "What does success mean to you?",
  "What does this world need more of? How can you help?",
  "What don’t you spend enough time doing?",
  "What give you hope?",
  "What happened to your childhood dream?",
  "What has been your favourite age so far and why?",
  "What have you started but never finished? Why?",
  "What have you witnessed that has strengthened your faith in humanity?",
  "What helps you to feel calm?",
  "What is a misconception that people have about you?",
  "What is a quirk that your family has?",
  "What is holding you back from doing the things you really want to do?",
  "What is a new habbit you want to form?",
  "What is one decision you made that changed your life?",
  "What is one moment that you want to relive?",
  "What is one place you want to travel to?",
  "What is one quality you wish you had?",
  "What is one question you would ask a fortune-teller?",
  "What is something new you have recently tried?",
  "What is something outside your comfort zone, that you would like to try?",
  "What is something you know that you do differently than most people?",
  "What is something you wish you didn't know?",
  "What is the best compliment you have been given?",
  "What is the best gift that someone can give you?",
  "What is the kindest thing someone has ever done for you?",
  "What is the most important lesson you have learnt?",
  "What is the strangest thing you have eaten?",
  "What is your biggest dream?",
  "What is your biggest fear?",
  "What is your earliest memory of achievement?",
  "What is your favourite place in the world?",
  "What is your greatest strength?",
  "What is your happiest memory?",
  "What is your next great adventure?",
  "What is your number one priority today?",
  "What gets you out of bed everyday?",
  "What little things in life do you take the time to stop and appreciate?",
  "What makes a friend a good/best friend?",
  "What makes you feel really alive?",
  "What makes you feel supported?",
  "What motivates you to keep going?",
  "What object would you save if your house was on fire?",
  "What was the most impactful event in your life?",
  "What were you doing the last time you lost track of time?",
  "What’s one thing that could happen today that would make it great?",
  "When was the last time you helped a stranger? Why?",
  "When was the last time you were moved to tears?",
  "Where do you find peace?",
  "Where would you like to wake up Tomorrow?",
  "Who do you need to get in touch with because it’s been too long?",
  "Who in your life do you love the most? and what are you doing about it?"
];

