const gameTitle = "Bad People";
const tableColour = '303030';
const cardColour = '000000';
const cardLogo = `url("https://www.egynomics.com/Images/BadPeople.png")`;

const theQuestions = [
  ["General","Who is most likely to join a cult"],
  ["General","Who is most likely to be childhood friends with Hitler"],
  ["General","Who is most likely to ask an overweight woman if she's pregnant"],
  ["General","Who is most likely to burn down their home for the insurance  money?"],
  ["General","Who will have the most divorces by the time they're 80?"],
  ["General","Who is most likely to laugh if they saw a blind person trip?"],
  ["General","Who is most likely to secretly run a meth lab?"],
  ["General","If we were hitchhikers, who would be the last person to get picked up?"],
  ["General","Who will be the most difficult old person to be around?"],
  ["General","If we were police officers, who would be the dirty cop?"],
  ["General","Who's most likely to run into a former partner and not remember their name?"],
  ["General","Who's funeral will have the smallest attendance?"],
  ["General","Who has the lowest standards?"],
  ["General","Who will make the smallest contribution to society in our lifetime?"],
  ["General","Who is most likely to date someone twice their age?"],
  ["General","Whose parents are the most disappointed in them?"],
  ["General","Who is most likely to get a tattoo and regret it later?"],
  ["General","Would leave the smallest tip at a restaurant?"],
  ["General","Who is most likely to lie about their age?"],
  ["General","If we were all in prison, who would rise to prison gang leader?"],
  ["General","Who is most likely to have a midlife crisis?"],
  ["General","Who is most likely to join a cult?"],
  ["General","Who has the best chance of cheating a lie detector test?"],
  ["General","Who is most likely to create a scam business?"],
  ["General","Who's the last person I'd want to be trapped in an elevator with?"],
  ["General","Who would think they're the most attractive person in the room?"],
  ["General","Who is most likely to say -- ILU -- too early?"],
  ["General","Who is most likely to call asking you to help them bury a dead body"],
  ["General","Who would be the worest motivational speaker?"],
  ["General","Who is most likely to be a Gold Digger?"],
  ["General","Who's the most high maintenance in a relationship?"],
  ["General","Who would be most likely to fall for a pyramid scheme?"],
  ["General","Who would be the worst person to work for?"],
  ["General","Who would to someone to get something they want?"],
  ["General","Who would get the most enjoyment from being a member of the opposite sex for a day?"],
  ["General","Who would most likely cheat while playing a board game?"],
  ["General","Who is the worst person to call for relationship advice?"],
  ["General","Who can't go 10 minutes without looking at themselves in the mirror?"],  
  ["General",""]
];