const gameTitle = "Make Big Talk";
const tableColour = '265834';
const cardColour = 'ffffff';
const cardLogo = `url("https://www.makebigtalk.com/wp-content/themes/blankslate/img/big-talk-logo-pos.svg")`;

const theQuestions = [
  ["General","As a kid, what scared you about growing up?"],
  ["General","Describe your perfect day"],
  ["General","Do you fit-in or Stand-out and how?"],
  ["General","Do you prefer swimming in the ocean or the pool?"],
  ["General","Do you prefer to watch or participate to learn something new?"],
  ["Adult"  ,"Do you want your children to be like you? Why?"],
  ["General","Have you ever had a near-death experience?"],
  ["General","Have you ever done something in a hurry and regretted it?"],
  ["General","How are you making a difference in the world?"],
  ["Adult"  ,"How do you deal with conflict at work or in love?"],
  ["General","How do you define true happiness?"],
  ["General","How do you feel about birthdays?"],
  ["General","How do you recharge when life gets difficult or overwhelming?"],
  ["Adult"  ,"How do you show love?"],
  ["General","How do you support your friends when they are upset?"],
  ["General","How old do you feel (regardless of your actual age)?"],
  ["General","If someone gave you $10,000 to spend, what would you do with it?"],
  ["General","If you came with a guarantee, what would it say?"],
  ["General","If you could create your own country, what would it be like?"],
  ["General","If you could have one super-power, what would it be and why?"],
  ["General","If you could invite three famous people to your home for dinner, who would they be?"],
  ["General","If you had 24 hours left to live, who would you be with in 23 hours?"],
  ["General","If you had 30 seconds to talk to the world what would you say?"],
  ["General","If you were to go back in history and live as someone else, who would it be, and why?"],
  ["General","If you were to go back in history and live, which time period, and why?"],
  ["General","If you wrote a one sentance mission statement about your life, what would it be?"],
  ["General","If your life was a book, what would be its title?"],
  ["General","Is there anyone in your life that you admire? Why?"],
  ["Adult"  ,"What about love makes you afraid?"],
  ["Adult"  ,"What advice would you give your younger self?"],
  ["General","What are three essential travel items you will never leave behind?"],
  ["General","What are you curious about lately?"],
  ["General","What are you looking forward to?"],
  ["General","What are you passionate about?"],
  ["General","What are you proud of?"],
  ["General","What are you thankful for at this very moment?"],
  ["Adult"  ,"What are you willing to sacrifice for love?"],  
  ["Adult"  ,"What are your boundaries?"],
  ["General","What attributes of your parents shaped you the most?"],
  ["General","What book changed your perspective?"],
  ["General","What concerns you about the future?"],
  ["General","What could you do today that you couldn't do a year ago?"],
  ["General","What do you do when you can't sleep at night?"],
  ["General","What do you believe in that you feel is different from others?"],
  ["General","What do you dream about?"],
  ["General","What do you fight for?"],
  ["General","What do you find fun?"],
  ["General","What do you find beautiful?"],
  ["General","What do you find challenging?"],
  ["General","What do you have that you cannot live without?"],
  ["General","What do you hope to achieve in five years?"],
  ["General","What do you miss?"],
  ["General","What do you most need help with?"],
  ["General","What do you spend too much time doing?"],
  ["General","What do you think about when you wake up?"],
  ["General","What do you think the world will be like in fifty years?"],
  ["General","What do you value that doesn't cost money?"],
  ["General","What do you want the world to remember about you?"],
  ["General","What do you want to change in the world?"],
  ["General","What do you want to do before you die?"],
  ["General","What do you wish more people knew about you?"],
  ["General","What does home mean to you?"],
  ["Adult"  ,"What does love mean to you?"],
  ["General","What does success mean to you?"],
  ["General","What does this world need more of? How can you help?"],
  ["General","What don’t you spend enough time doing?"],
  ["General","What fictional place would you most like to visit/live in?"],
  ["General","What food could you eat every day?"],
  ["General","What gets you out of bed every day?"],
  ["General","What gives you hope?"],
  ["Adult"  ,"What happened to your childhood dream?"],
  ["Adult"  ,"What has been your favourite age so far and why?"],
  ["General","What have you learnt from your past mistakes?"],
  ["General","What have you started but never finished? Why?"],
  ["General","What have you witnessed that has strengthened your faith in humanity?"],
  ["General","What helps you to feel calm?"],
  ["General","What is a bad habit you would like to break?"],
  ["General","What is a feeling you miss?"],
  ["General","What is a goal you plan on accomplishing this year?"],
  ["General","What is a life lesson a grandparent tought you?"],
  ["General","What is a misconception that people have about you?"],
  ["General","What is a new habit you want to form?"],
  ["General","What is a quirk that your family has?"],
  ["Adult"  ,"What is an underrated way of showing affection?"],
  ["General","What is difficult for you now, but was easy as a child?"],
  ["General","What is holding you back from doing the things you really want to do?"],
  ["General","What is one decision you made that changed your life?"],
  ["General","What is one moment that you want to relive?"],
  ["General","What is one place you want to travel to?"],
  ["General","What is one quality you wish you had?"],
  ["General","What is one question you would ask a fortune-teller?"],
  ["General","What is one thing that could happen today that would make it great?"],
  ["General","What is one thing you would never compromise on?"],
  ["General","What is something new you have recently tried?"],
  ["General","What is something outside your comfort zone, that you would like to try?"],
  ["General","What is something you forgot once, and will never forget again?"],
  ["General","What is something you know that you do differently than most people?"],
  ["General","What is something you learnt about yourself from your past relationships?"],
  ["General","What is something you wish you didn't know?"],
  ["General","What is the best conversation piece in your home?"],
  ["General","What is the best gift someone can give you?"],
  ["General","What is the best gift you have ever received?"],
  ["General","What is the best way to spend a cold day?"],
  ["General","What is the best way to spend a sunny day?"],
  ["General","What is the biggest risk you have taken?"],
  ["General","What is the kindest thing someone has ever done for you?"],
  ["General","What is the most breathtaking view you have seen?"],
  ["General","What is the most important lesson you have learnt?"],
  ["Adult"  ,"What is the most important trait in your ideal partner?"],
  ["General","What is the weirdest gift you have ever given or received?"],
  ["General","What is the strangest thing you have eaten?"],
  ["General","What is your biggest fear?"],
  ["General","What is your earliest childhood memory?"],
  ["General","What is your earliest memory of achievement?"],
  ["General","What is your favourite place in the world?"],
  ["General","What is your greatest strength?"],
  ["General","What is your happiest memory?"],
  ["General","What is your least favourite chore?"],
  ["General","What is your most annoying habit?"],
  ["General","What is your most favourite chore?"],
  ["General","What is your most favourite desert?"],
  ["General","What is your next great adventure?"],
  ["General","What is your number one priority today?"],
  ["General","What is your usual coping method when you are sad?"],
  ["General","What job would you choose if money was not a consideration?"],
  ["General","What little things in life do you take the time to stop and appreciate?"],
  ["General","What makes a friend a good/best friend?"],
  ["General","What makes you feel really alive?"],
  ["General","What makes you feel supported?"],
  ["General","What motivates you to keep going?"],
  ["General","What new law would you like to make?"],
  ["General","What object would you save if your house was on fire?"],
  ["General","What rule do you like breaking?"],
  ["General","What rule do you think should not exist?"],
  ["General","What song makes you want to dance?"],
  ["General","What topic could you talk about for thirty minutes with no preparation?"],
  ["General","What was the best compliment you have received?"],
  ["General","What was the most impactful event in your life?"],
  ["Adult"  ,"What was your secret spot or hideaway as a child?"],
  ["General","What were you doing the last time you lost track of time?"],
  ["General","What would you do if you won the lottery?"],
  ["Adult"  ,"What would you not tolerate in a relationship?"],
  ["General","What would you regert not having done by the end of your life?"],
  ["General","When do you feel the most like yourself?"],
  ["General","When was the last time someone made you smile?"],
  ["General","When was the last time you helped a stranger? Why?"],
  ["General","When was the last time you lied? Why?"],
  ["General","When was the last time you made someone else smile?"],
  ["General","When was the last time you were moved to tears?"],
  ["General","Where do you find peace?"],
  ["General","Where would you like to wake up Tomorrow?"],
  ["General","Which hour of the day would you want to skip completely?"],
  ["General","Which vacation exceeded your expectations and why?"],
  ["General","Who do you need to get in touch with because it’s been too long?"],
  ["General","Who do  you turn to for support?"],
  ["General","Who is your hero or role-model?"],
  ["General","Who in your life do you love the most? and what are you doing about it?"],
  ["General","Why do you do what you do?"]
];